# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
