# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0015_auto_20160926_1425'),
        ('Home', '0002_auto_20160926_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='Cards.Cards'),
        ),
    ]
