# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsinfo',
            name='attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cardsinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cardsinfo',
            name='due_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='cardsinfo',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cardsinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
