# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_auto_20160819_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsinfo',
            name='activity',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='cardsinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
