# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0004_auto_20160822_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsinfo',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
