# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0006_auto_20160822_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('data', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='database',
            field=models.ManyToManyField(to='Cards.Data'),
        ),
    ]
