# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0007_auto_20160823_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='cardid',
            field=models.IntegerField(default=1),
        ),
    ]
