# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0008_cards_cardid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='cardid',
        ),
    ]
