# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0009_remove_cards_cardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='database',
            field=models.ManyToManyField(related_name='databs', to='Cards.Data'),
        ),
    ]
