# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0010_auto_20160823_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(null=True, upload_to='')),
                ('attachment', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='CardsInfo',
        ),
    ]
