# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0012_cards_card_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('list_date', models.DateField(default=datetime.datetime(2016, 9, 19, 13, 37, 43, 662954))),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('Check_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.Checklist')),
            ],
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 19, 13, 37, 43, 678589)),
        ),
        migrations.AddField(
            model_name='data',
            name='checklist',
            field=models.ManyToManyField(related_name='checklist', to='Cards.ChecklistItems'),
        ),
    ]
