# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0013_auto_20160919_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 19, 13, 41, 5, 904040)),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='list_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 19, 13, 41, 5, 901521)),
        ),
    ]
