# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0014_auto_20160919_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 26, 14, 25, 40, 562958)),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='list_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 26, 14, 25, 40, 557955)),
        ),
    ]
