# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0015_auto_20160926_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='list_date',
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 4, 12, 56, 57, 492000)),
        ),
    ]
