# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0021_auto_20161105_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 5, 1, 54, 4, 213709)),
        ),
    ]
