# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0022_auto_20161105_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 5, 1, 56, 15, 402689)),
        ),
    ]
